Repository knightempire/lab-frontend, pull requests merged in 2025-05, with the labels that each got.

#18 Added user page for admin
  src/app/admin/users/page.js
  src/app/auth/login/page.js
  src/components/Sidebar.js
  src/components/table.js
Labels: Component, Feature, UI design

#22 Serial Number Changes
  src/app/admin/product/page.js
  src/app/admin/users/page.js
  src/app/layout.js
  src/app/user/product/page.js
  src/components/pagination.js
  src/components/table.js
Labels: enhancement

#29 Fixed bug in admin/users page
  src/app/admin/users/page.js
Labels: bug

#38 Updated pagination update during searching
  src/app/admin/product/page.js
  src/app/admin/request/page.js
  src/app/admin/users/page.js
  src/app/user/product/page.js
Labels: bug

#49 update style in 404
  src/app/not-found.js
Labels: UI design

#59 Updated Checkoutpage and product page
  src/app/user/checkout/page.js
  src/app/user/product/page.js
Labels: bug, enhancement

#99 auth model fix
  src/app/auth/password/page.js
Labels: bug

#124 Admin request and review page modifications
  src/app/admin/request/page.js
  src/app/admin/review/page.js
  src/components/Navbar.js
  src/components/Sidebar.js
  src/components/SuccessAlert.js
Labels: enhancement, Component
